import type { Metadata } from "next";
import MainLayout from "./components/MainLayout/MainLayout";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "@/app/globals.scss";
export const metadata: Metadata = {
  title: "Demo",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <MainLayout>{children}</MainLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
